services:
  worker_management_service:
    build:
      context: ../..
      dockerfile: "../PDF-Microservices/PDF-Microservices-Worker-Management-Service/dockerfile"
      tags:
        - worker_management_service:latest
        #    image: 'worker_management_service:latest'
    networks:
      - backend-network
      - pdf_microservice_arch
      - backend-logging-connector
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - 'EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://job-service-eureka-1:8761/eureka/'
      - 'PAGES_PER_JOB=10'
      - 'EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5'
      - 'EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10'
    depends_on:
      eureka:
        condition: service_healthy

  worker_service:
    build:
      context: ../..
      dockerfile: "../PDF-Microservices/PDF-Microservices-Worker-Service/dockerfile"
      tags:
        - worker_service:latest
        #    image: "worker_service:latest"
    networks:
      - backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - '6000:6000'
    environment:
      - 'SPRING_PROFILES_ACTIVE=default'
      - 'SPRING_APPLICATION_NAME=WorkerServiceNode'
      - 'EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://job-service-eureka-1:8761/eureka/'
      - 'EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5'
      - 'EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10'
    depends_on:
      eureka:
        condition: service_healthy

  eureka:
    build:
      context: ../..
      dockerfile: "../PDF-Microservices/PDF-Microservices-Eukrea/dockerfile"
      tags:
        - eureka_instance:latest
        #    image: "eureka_instance:latest"
    networks:
      - backend-network
      - pdf_microservice_arch
    environment:
      - 'EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS=5000'
      - 'EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false' #Change in deployment!
      - 'EUREKA_CLIENT_FETCH_REGISTRY=true'
      - 'EUREKA_CLIENT_REGISTER_WITH_EUREKA=true'
    ports:
      - '8761:8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: 'rabbitmq:3-management'
    networks:
      - backend-network
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'

networks:
  pdf_microservice_arch:
    external: true
  backend-network:
    external: false
  backend-logging-connector:
    external: true